import './globals.css'
import type { Metadata } from 'next'
import Provider from '@/components/provider'


export const metadata: Metadata = {
  title: 'altaf.syah || personal space',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Provider>
        {children}
      </Provider>
    </html>
  )
}
